schema_version = "1.0.0"

id = "pichan_texture_updater"
version = "1.0.0"
name = "PiChan Texture Updater"
tagline = "Update textures on selected objects from an external folder"
maintainer = "PiChan Studio"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
tags = ["Material"]
